### ISSUE TITLE
Fix link to Documentation

### ISSUE THREAD

**Issue by ninabreznik** [SynBioDex/sboljs#14]
Unfortunately there's a broken link here. http://ico2s.github.io/sboljs Would love to read more...

**Comment by nathanwilk7** [comment]
Fixed, though documentation still needs to be updated

**Comment by nathanwilk7** [comment]
@ninabreznik active development on sboljs has recently started up again and I wanted to reach out to you and touch base. I apologize for the length of time that passed before you were contacted regarding the issue you logged.

Are you still interested in using sboljs? If so, please feel free to reach out to me with any questions you have or post them here. I am happy to assist in any way possible. I would be happy to walk through some examples of using the sboljs library as well.
