### ISSUE TITLE
Readme example fails for several examples listed on standard page + docs down

### ISSUE THREAD

**Issue by maxbates** [SynBioDex/sboljs#22]
I was looking at using SBOLjs for a simple converter, but I am running into several problems, notably:

- The documentation website is not working. How does someone look up docs for this package?
- The example script given in the ReadMe fails for several (all the ones I tried) examples listed at http://sbolstandard.org/data-model-examples/ . Perhaps if docs we were working it would be clearer how to go about parsing a file, but it appears that the documents are simply parsed to a list of top level components. 

It is unclear to me how to use this package, and in particular what parsing limitations it has (versions unsupported, SBOL features not supported, subjective estimates of how frequently there are issues parsing...)

Are these examples expected to work? A few working examples would be enormously helpful.

**Comment by nathanwilk7** [comment]
@maxbates active development on sboljs has recently started up again and I wanted to reach out to you and touch base. I apologize for the length of time that passed before you were contacted regarding the issue you logged. The example script given in the readme now works correctly and the documentation link has been updated. One side note, the API documentation does not include a few of the newer classes that have been added. Currently, the best place to look for examples of how to use the sboljs library are [here](http://sbolstandard.org/libsbol/) and in the test directory of the sboljs GitHub repo.

Are you still interested in using sboljs? If so, please feel free to reach out to me with any questions you have or post them here. I am happy to assist in any way possible. I would be happy to walk through some examples of using the sboljs library as well.
